"""
Database Package for Randol's Agentic Marketing Platform
"""

from .models import (
    ABTest,
    AgentLog,
    AgentState,
    AgentStatus,
    AuditLog,
    ContentBase,
    ContentCalendar,
    ContentCreate,
    ContentInDB,
    ContentMedia,
    ContentMetrics,
    ContentResponse,
    ContentStatus,
    ContentType,
    ContentValidation,
    DailyAnalytics,
    EmergencyOverride,
    Notification,
    Platform,
    PlatformAnalytics,
    ScheduledPost,
    SystemConfig,
    WeeklyReport,
    deserialize_doc,
    serialize_doc,
)
from .repository import (
    AgentRepository,
    AnalyticsRepository,
    ContentRepository,
    DatabaseManager,
    NotificationRepository,
    ScheduleRepository,
    db_manager,
    initialize_database,
)

__all__ = [
    # Enums
    "ContentStatus",
    "Platform",
    "ContentType",
    "AgentStatus",
    # Models
    "ContentMedia",
    "ContentMetrics",
    "ContentValidation",
    "ContentBase",
    "ContentCreate",
    "ContentInDB",
    "ContentResponse",
    "ScheduledPost",
    "ContentCalendar",
    "PlatformAnalytics",
    "DailyAnalytics",
    "WeeklyReport",
    "AgentLog",
    "AgentState",
    "ABTest",
    "AuditLog",
    "EmergencyOverride",
    "Notification",
    "SystemConfig",
    # Utilities
    "serialize_doc",
    "deserialize_doc",
    # Database
    "DatabaseManager",
    "db_manager",
    "ContentRepository",
    "ScheduleRepository",
    "AnalyticsRepository",
    "AgentRepository",
    "NotificationRepository",
    "initialize_database",
]
